spring:
  application:
    name: mail
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/mail
    username: root
    password: 123456
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 1024MB
      #单个请求最大文件大小
      max-request-size: 10240MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql

gateway:
  id: ID1
  email-suffix: aa.com
  routers:
    - suffix: bb.com
      gateway-id: ID2
      short-address: VA:2KDNQ2GYEIWIS4OZEMAGJ3LDULCWK3A6W3SWDP4DPYGBOXPG3AYQ

    - suffix: cc.com
      gateway-id: ID3
      short-address: VA:WTK3WZTFHSJUXMJCL3JYLCOVMZKNLBIHBKRJLTYEO3VMBXIZEZ7Q

# 有关文件的配置信息
file:
  upload-dir: /app/file_buffer
  aes-key: zSbcY8W5CVqtUNtZ2UB8zA==
  security-dir: /app/file_buffer/security_store
# 与monitor集成的代码
monitor:
  monitor-host: 10.1.160.104
  monitor-port: 9092

# 集成吴睿师姐校验授权
auth:
  radius-server: 10.1.160.104
  radius-secret: testing123
  ca-cert: ./auth/ca.pem
  client-cert: ""
  client-key: ""
  nas-ip-address: 127.0.0.1
  dictionary-path: ./auth/radius_dictionary
  public-key-path: ./auth/public_key.pem

  method: password
  username:
  password:
  mac: ""
  cert: ""
  key: ""
  keypass: ""
  exe-path: ./auth/certification
