spring:
  application:
    name: mail
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway-database:3306/mail
    username: root
    password: 123456
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 1024MB
      #单个请求最大文件大小
      max-request-size: 10240MB
server:
  port: 8080
  
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql

gateway:
  id: ID1
  email-suffix: aa.com
  routers:
    - suffix: bb.com
      gateway-id: ID2

    - suffix: cc.com
      gateway-id: ID3

# 有关文件的配置信息
file:
  upload-dir: /app/file_buffer
  aes-key: zSbcY8W5CVqtUNtZ2UB8zA==
  security-dir: /app/file_buffer/security_store
# 与monitor集成的代码

monitor:
  monitor-host: host.docker.internal
  monitor-port: 9092

auth:
  radius-server: gateway-auth-server
  radius-secret: testing123
  ca-cert: ./auth/ca.pem
  client-cert: ""
  client-key: ""
  nas-ip-address: 192.168.0.5
  dictionary-path: ./auth/radius_dictionary
  public-key-path: ./auth/public_key.pem
  auth_port: 1812
  acct_port: 1813
  coa_port: 3799
  method: password
  username:
  password:
  mac: ""
  cert: ""
  key: ""
  keypass: ""
  exe-path: ./auth/certification
